[package]
edition = { workspace = true }
name    = "mpc-coordinator"
version = "0.1.0"

[dependencies]
clap               = { workspace = true, features = ["derive"] }
hex                = { workspace = true }
mpc-shared         = { workspace = true }
pgp                = "0.13"
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "tracing-log"] }
