[package]
edition = "2021"
name    = "voyager-client-module-cometbls"
version = "0.1.0"

[dependencies]
alloy                       = { workspace = true, features = ["sol-types"] }
ark-bn254                   = { version = "0.4", default-features = false, features = ["curve"] }
ark-serialize               = "0.4.2"
cometbls-light-client-types = { workspace = true, features = ["proto", "ethabi", "serde"] }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
macros                      = { workspace = true }
num-bigint                  = { workspace = true }
protos                      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }

[dev-dependencies]
bcs.workspace         = true
hex-literal.workspace = true
hex.workspace         = true
