[package]
edition = "2021"
name    = "voyager-consensus-module-ethereum"
version = "0.1.0"

[dependencies]
alloy            = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
beacon-api       = { workspace = true }
beacon-api-types = { workspace = true, features = ["serde"] }
jsonrpsee        = { workspace = true, features = ["macros", "server", "tracing"] }
serde            = { workspace = true, features = ["derive"] }
tokio            = { workspace = true }
tracing          = { workspace = true }
unionlabs        = { workspace = true }
voyager-message  = { workspace = true }
voyager-vm       = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
