[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "union-ibc-movement-lc"
repository   = { workspace = true }
version      = "0.1.0"

[dependencies]
aptos-verifier              = { workspace = true }
bcs                         = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["abort"] }
evm-storage-verifier        = { workspace = true }
hex-literal                 = { workspace = true }
movement-light-client-types = { workspace = true, features = ["ethabi", "serde"] }
rlp                         = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde-utils                 = { workspace = true }
thiserror                   = { workspace = true }
union-ibc-light-client      = { workspace = true }
union-ibc-msg               = { workspace = true }
unionlabs                   = { workspace = true }

[dev-dependencies]
aptos-crypto = { workspace = true }
aptos-types  = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library        = []
union-movement = []
