[package]
authors      = ["Union Labs"]
edition      = "2021"
license-file = { workspace = true }
name         = "arbitrum-light-client"
publish      = false
version      = "0.1.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arbitrum-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
arbitrum-verifier           = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
ethereum-light-client       = { workspace = true, features = ["library"] }
ethereum-light-client-types = { workspace = true }
thiserror                   = { workspace = true }
union-ibc-light-client      = { workspace = true }
union-ibc-msg               = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64     = { workspace = true }
hex        = { workspace = true }
serde_json = { workspace = true }

[features]
library = []
