[package]
edition      = { workspace = true }
include      = [".sqlx"]
license-file = { workspace = true }
name         = "voyager"
publish      = false
repository   = { workspace = true }
resolver     = "2"
version      = "0.1.0"

[package.metadata.crane]
test-include = []

[lints]
workspace = true

[dependencies]
anyhow                     = "1.0.93"
axum                       = { workspace = true, features = ["macros", "tokio", "json"] }
clap                       = { workspace = true, features = ["default", "derive", "env", "error-context", "color"] }
derive_more                = { workspace = true }
frame-support-procedural   = { workspace = true }
futures                    = { workspace = true }
ibc-classic-spec.workspace = true
ibc-union-spec.workspace   = true
jsonrpsee                  = { workspace = true, features = ["client", "full", "tracing"] }
pg-queue                   = { workspace = true }
pin-utils                  = "0.1.0"
prometheus                 = "0.13.4"
reqwest                    = { workspace = true, features = ["tokio-rustls"] }
schemars                   = { workspace = true }
serde                      = { workspace = true, features = ["derive"] }
serde_json                 = { workspace = true }
sqlx                       = { workspace = true, features = ["postgres", "migrate", "tls-rustls"] }
thiserror                  = { workspace = true }
tikv-jemallocator          = "0.5"
tokio                      = { workspace = true, features = ["macros"] }
tracing                    = { workspace = true, features = ["max_level_trace"] }
tracing-futures            = { version = "0.2.5", features = ["futures-03"] }
tracing-subscriber         = { workspace = true, features = ["env-filter", "json"] }
unionlabs                  = { workspace = true, features = ["ethabi"] }
voyager-message            = { workspace = true }
voyager-vm                 = { workspace = true }

[features]
default = []
