[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ucs01-relay"
publish      = false
repository   = { workspace = true }
version      = "1.0.1"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
base58            = { version = "0.2" }
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true, features = ["stargate", "cosmwasm_2_1", "abort"] }
cw-controllers    = { version = "2.0.0" }
cw-storage-plus   = { workspace = true }
cw2               = { version = "2.0.0" }
hex               = { workspace = true }
ibc-solidity      = { workspace = true, features = ["serde"] }
prost             = { workspace = true }
protos            = { workspace = true }
serde             = { workspace = true, features = ["derive"] }
serde-json-wasm   = { workspace = true }
sha2              = { workspace = true }
thiserror         = { workspace = true }
token-factory-api = { workspace = true }
ucs01-relay-api   = { workspace = true }
union-ibc-msg     = { workspace = true }
unionlabs         = { workspace = true }

[dev-dependencies]
cw-multi-test = { git = "https://github.com/CosmWasm/cw-multi-test.git", rev = "e1a2f587c7f9d723444ec93ad8fa48f1d88b65bc", features = ["stargate", "staking"] }
