[package]
edition = "2021"
name    = "voyager-consensus-module-cometbls"
version = "0.1.0"

[dependencies]
cometbft-rpc    = { workspace = true }
jsonrpsee       = { workspace = true, features = ["macros", "server", "tracing"] }
serde           = { workspace = true, features = ["derive"] }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
unionlabs       = { workspace = true }
voyager-message = { workspace = true }
voyager-vm      = { workspace = true }
