[package]
edition = "2021"
name    = "voyager-client-module-movement"
version = "0.1.0"

[dependencies]
chain-utils                 = { workspace = true }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
movement-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
thiserror                   = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true }
voyager-message             = { workspace = true }
