[package]
edition = "2021"
name    = "voyager-proof-module-ethereum"
version = "0.1.0"

[dependencies]
alloy                       = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws"] }
ethereum-light-client-types = { workspace = true }
ibc-union-spec.workspace    = true
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }
